branch-defaults:
  master:
    environment: aws-php-sample-dev
    group_suffix: null
global:
  application_name: aws_php_sample
  branch: null
  default_ec2_keyname: null
  default_platform: PHP 7.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
